export default {
    products: [
      {
        _id: '111111111111111111111111',
        name:'Red digital smartwatch',
        category: 'Demo Products',
        image: '/img/product-1.jpg',
        price: 60,
        desc: 'Gridiculus mus. Vestibulum Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ultricies aliquam convallis.',
        brand: 'Nike',
        rating: 4.5,
        numReviews: 50,
        countInStock: 36,
        tags: 'classic',
      },
      {
        _id: '222222222222222222222222',
        name:'Jacket Shirts',
        category: 'Shirts',
        image: '/img/product-2.jpg',
        price: 70,
        desc: 'parturient montes nascetur ridLorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis iculus mus. Vestibulum ultricies aliquam convallis.',
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 4,
        tags: 'Fashion',
      },
      {
        _id: '333333333333333333333333',
        name:'Full Zip Running Shirts',
        category: 'Demo Products',
        image: '/img/product-3.jpg',
        price: 60,
        desc: 'lor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatLorem ipsum doibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        countInStock: 32,
        tags: 'Hottie',
      },
      {
        _id: '444444444444444444444444',
        name:'Kui Ye Chen’s AirPods',
        category: 'Shirts',
        image: '/img/product-4.jpg',
        price: 40,
        desc: 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        brand: 'Nike',
        rating: 4.5,
        numReviews: 19,
        countInStock: 60,
        tags: 'classic',
      },
      {
        _id: '555555555555555555555555',
        name:'Fashion Wrist watch',
        category: 'Demo Products',
        image: '/img/product-5.jpg',
        price: 190,
        desc: 'Lorem ipsum it. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        brand: 'Nike',
        rating: 4.5,
        numReviews: 31,
        countInStock: 16,
        tags: 'Stylish',
      },
      {
        _id: '666666666666666666666666',
        name:'Big Touser',
        category: 'Shoe',
        image: '/img/product-6.jpg',
        price: 160,
        desc: 'et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.',
        brand: 'Nike',
        rating: 4.5,
        numReviews: 15,
        countInStock: 0,
        tags: 'Best Price',
      },
    ],
};
